### ISSUE TITLE
Research Touch functionality and come up with best practices

### ISSUE THREAD

**Issue by LeonidLevi** [wix/stylable-components#113]
- See what kind of touch-specific handling we want to create for all of the components
- See if we have some general guidelines
-- which events to use? 
-- Do we observe the 300ms delay?
-- Conflicts between touch, drag/swipe? Do we resolve or leave it to the browser?
-- Remapping of hover to touch?
-- Tap event? Should we trigger it on touch release or differently?
-- Long touch handling?
-- Force touch handling?
- How do we test our components on touch devices?

**Comment by wtfil** [comment]
This is an example of how to make hover for both mobile and desktop via `@media (hover: *)`
![image](https://user-images.githubusercontent.com/1421128/29173148-05338428-7deb-11e7-94ab-a7d4f7399d4e.png)

![image](https://user-images.githubusercontent.com/1421128/29173105-e1880f08-7dea-11e7-913a-e85f24f1de54.png)

```css
.root {
    background: green;
}

@media (hover: hover) {
    .root:hover {
        background: orange;
    }
}

@media (hover: none) {
    .root:active {
        background: orange;
    }
}
```

**Comment by wtfil** [comment]
The `mousedown`, `mouseup` and `click` will fire on mobile without any delay (all browsers supports this now, so no need of fastclick and cetera)
However, these events will not fire when user make long click.
So the best practice will be attach to `touchdown` and `touchup`
Here is a demo https://jsbin.com/mefetadufo/4

**Comment by wtfil** [comment]
The hover status mainly discussed [here](https://github.com/wixplosives/stylable-components-guide/issues/13) 
Mobile devices does not works well with `:hover`. To achieve this effect on mobile you have to use `:active`
The best way to do this is to use `@media (hover: none)` media query.
```css
.elem {
  background: green;
}
.elem:hover {
  background: red;
}
@media {
  /* reset hover on mobile */
  .elem:hover {
    background: green; 
  }
  .elem:active {
    background: red;
  }
}
```

unfortunately we can not use `media (hover: hover) {}` to add `:hover` for browsers which actually supports `:hover` because some of them might support `:hover` but does not support the `@media (hover: hover) {}`. So the best way is to attach `:hover` for anyone and than reset it
