### ISSUE TITLE
theme sets color to label globally

### ISSUE THREAD

**Issue by DeDuckProject** [wix/stylable-components#336]
I'm using the stylable-components' default-theme.
It sets label's text like so:
```css
.project3855525739💠root label {
    color: #577083;
    font-size: 16px;
    line-height: 24px;
}
```

This is problematic in cases where I change the background of a containing element. the color should be context dependent.

this is what happens:

![image](https://user-images.githubusercontent.com/10045034/30533281-2ea0f5cc-9c61-11e7-83e1-e9a7ae5334bf.png)
Notice the label "Kishkashta" which stays in the grey-ish even though the containing element sets the color to white
```css
.container{
    background: rgb(50, 83, 106);
    color: white;
}
```
